---
description: 'Altre informazioni su: C6318'
title: C6318
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C6318
helpviewer_keywords:
- C6318
ms.assetid: 3284a83e-bb8e-461c-adcc-cfc66ceea05e
ms.openlocfilehash: 07a7039693f5c4b8163a266e0764b981085685bd
ms.sourcegitcommit: d6af41e42699628c3e2e6063ec7b03931a49a098
ms.translationtype: MT
ms.contentlocale: it-IT
ms.lasthandoff: 12/11/2020
ms.locfileid: "97332621"
---
# <a name="c6318"></a>C6318

> avviso C6318: __try/_except definito in modo non corretto \_ : utilizzo della costante EXCEPTION_CONTINUE_SEARCH o di un'altra costante che restituisce zero nell'espressione di filtro eccezioni. Il codice nel blocco del gestore eccezioni non viene eseguito

Questo avviso indica che se si verifica un'eccezione nel blocco protetto di questo gestore di eccezioni strutturate, l'eccezione non verrà gestita perché la costante `EXCECPTION_CONTINUE_SEARCH` viene utilizzata nell'espressione di filtro delle eccezioni.

Questo codice è equivalente al blocco protetto senza il blocco del gestore eccezioni perché il blocco del gestore non viene eseguito.

## <a name="example"></a>Esempio

Il codice seguente genera questo avviso:

```cpp
#include <excpt.h>
#include <stdio.h>

void f (char *pch)
{
  __try
  {
    // assignment might fail
    *pch = 0;
  }
  __except (EXCEPTION_CONTINUE_SEARCH) // warning C6318
  {
    puts("Exception Occurred");
  }
}
```

Per correggere il problema, usare il codice seguente:

```cpp
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *pch)
{
  __try
  {
    // assignment might fail
    *pch = 0;
  }
  __except( (GetExceptionCode() == EXCEPTION_ACCESS_VIOLATION) ?
                EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH )
  {
    puts("Access violation");
  }
}
```

## <a name="see-also"></a>Vedi anche

[Istruzione try-except](../cpp/try-except-statement.md)
